include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore

linter:  
  rules:
    avoid_print: true
    avoid_empty_else: true
    prefer_const_constructors: true
    invalid_annotation_target: ignore
    use_key_in_widget_constructors: true
