trigger:
  - development
pool:
  vmImage: 'ubuntu-latest'


# Flutter build
variables:
  projectDirectory: sample_project

jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '21'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Hey24sheep.flutter.flutter-install.FlutterInstall@0
    - task: Hey24sheep.flutter.flutter-build.FlutterBuild@0
      inputs:
        target: apk
        

    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1