name: taskaty
version: 1.0.0+3
description: "Task Management App"

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use for Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  requests_inspector: 4.0.2
  get_storage: ^2.1.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  equatable: ^2.0.5
  path_provider: ^2.1.3
  json_annotation: 4.9.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.6
  file_picker: ^8.0.3
  image_picker: 1.1.1
  flutter_screenutil: ^5.9.0
  go_router: ^14.1.0
  fluttertoast: ^8.2.5
  badges: ^3.1.2
  pinput: ^4.0.0
  lottie: ^3.1.2
  percent_indicator: ^4.2.3
  dropdown_button2: ^2.3.9
  webview_flutter: ^4.7.0
  dotted_border: ^2.1.0

  flutter_intl: ^0.0.1
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.3
  material_segmented_control: ^5.0.1
  fl_chart: ^0.68.0
  connectivity_plus: ^5.0.2
  animation_list: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  build_runner: ^2.4.10
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.3.10
  json_serializable: 6.8.0
  riverpod_generator: ^2.4.0
  freezed_annotation: ^2.4.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/applogo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/cairo/
    - assets/icons/
    - assets/icons/files/
    - assets/images/
    - assets/json/
    - assets/json/notasks.json

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Black.ttf
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/cairo/Cairo-Light.ttf
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf

flutter_intl:
  enabled: true
  arb_dir: lib/config/l10n/i18n
  output_dir: lib/config/l10n/generated
#  fonts:
#    - family: Cairo
#      fonts:
#        - asset: assets/fonts/cairo/Cairo-Black.ttf
#        - asset: assets/fonts/cairo/Cairo-Bold.ttf
#        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
#        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
#        - asset: assets/fonts/cairo/Cairo-Light.ttf
#        - asset: assets/fonts/cairo/Cairo-Medium.ttf
#        - asset: assets/fonts/cairo/Cairo-Regular.ttf
#        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf