name: taskaty
version: 1.0.4+8
description: "Task Management App"

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:

    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  firebase_messaging: ^14.0.0
  firebase_core: ^2.28.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  provider: ^6.1.2
  timeago: ^3.7.0
  flutter_local_notifications: ^17.2.3
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
